server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # THE MAGIC WIRING: If the file isn't found, fallback to React's index.html!
        try_files $uri $uri/ /index.html;
    }

    # Optional: Ignore missing favicon errors
    location = /favicon.ico { log_not_found off; access_log off; }
}