# -----------------------------------------------------------
# RATING SERVICE (main2.py)
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  labels:
    app: rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
        annotations: # ADD THIS BLOCK
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: rating
        image: ttl.sh/lumina-backend-vgu:v10
        imagePullPolicy: Always
        env:
        - name: PYTHONPATH
          value: "/app" 
        command: ["uvicorn", "rating_service.main2:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  selector:
    app: rating
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

---
# -----------------------------------------------------------
# REVIEW SERVICE v1 (Basic Reviews)
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service-v1
  labels:
    app: review
    version: v1
  annotations: # ADD THIS BLOCK
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
      version: v1
  template:
    metadata:
      labels:
        app: review
        version: v1
      annotations: # ADD THIS BLOCK
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: review
        image: ttl.sh/lumina-backend-vgu:v10
        imagePullPolicy: Always
        env:
        - name: PYTHONPATH
          value: "/app"
        command: ["uvicorn", "review_service.v1.main3version1:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000

---
# -----------------------------------------------------------
# REVIEW SERVICE v2 (Sentiment Analysis)
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service-v2
  labels:
    app: review
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
      version: v2
  template:
    metadata:
      labels:
        app: review
        version: v2
      annotations: # ADD THIS BLOCK
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: review
        image: ttl.sh/lumina-backend-vgu:v10
        imagePullPolicy: Always
        env:
        - name: PYTHONPATH
          value: "/app"
        command: ["uvicorn", "review_service.v2.main3version2:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000

---
# Single Service pointing to BOTH Review versions
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  selector:
    app: review 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000